# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    providers:
        jwt:
            lexik_jwt:
                class: CoreBundle\Infrastructure\Symfony\Security\Model\Entity\AuthUser

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
            stateless:  true

        secured_area:
            pattern:    ^/api/
            stateless: true
            provider: jwt
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
    access_control:
        - { path: ^/,     roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/doc,     roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/,  roles: IS_AUTHENTICATED_FULLY       }